export const schemaTypes = [
    { key: 0,  value: 'article',  text: 'Article' },
    { key: 1,  value: 'techarticle',  text: 'TechArticle' },
    { key: 2,  value: 'newsarticle',  text: 'NewsArticle' },
    { key: 3,  value: 'advertisercontentarticle',  text: 'AdvertiserContentArticle' },
    { key: 4,  value: 'satiricalarticle',  text: 'SatiricalArticle' },
    { key: 5,  value: 'scholarlyarticle',  text: 'ScholarlyArticle' },
    { key: 6,  value: 'socialmediaposting',  text: 'SocialMediaPosting' },
    { key: 7,  value: 'product',  text: 'Product' },
    { key: 8,  value: 'softwareapplication',  text: 'SoftwareApplication' },
    { key: 9, value: 'book', text: 'Book' },
    { key: 10, value: 'faqpage', text: 'FAQs'},    
    { key: 11, value: 'howto', text: 'HowTo'},    
    { key: 12, value: 'qna', text: 'Q&A' },
    { key: 13, value: 'event', text: 'Event' },
    { key: 14, value: 'recipe', text: 'Recipe' },
    { key: 15, value: 'videoobject', text: 'VideoObject' },
    { key: 16, value: 'course', text: 'Course' },
    { key: 17, value: 'jobposting', text: 'JobPosting' },
    { key: 18, value: 'localbusiness', text: 'LocalBusiness' },
    { key: 19, value: 'service', text: 'Service' },
    { key: 20, value: 'broadcastservice', text: 'BroadcastService' },
    { key: 21, value: 'cableorsatelliteservice', text: 'CableOrSatelliteService' },
    { key: 22, value: 'financialproduct', text: 'FinancialProduct' },
    { key: 23, value: 'foodservice', text: 'FoodService' },
    { key: 24, value: 'governmentservice', text: 'GovernmentService' },
    { key: 25, value: 'taxiservice', text: 'TaxiService' },
    { key: 26, value: 'webapi', text: 'WebAPI' },
]