<?php
// Exit if accessed directly
if ( ! defined( 'ABSPATH' ) ) exit;

//Expose Jsonld in WPGraphQL starts here

add_action( 'graphql_register_types', 'smpg_register_jsonld_wpgraphql_field' );

/**
 * Register `jsonld` GraphQL field if the option is enabled.
 */
function smpg_register_jsonld_wpgraphql_field() {
    
    global $smpg_settings; 
    
    if ( ! empty( $smpg_settings['wpgraphql_cmp'] ) ) {
        
        $post_types = apply_filters( 'smpg_jsonld_wpgraphql_for_post_types', ['post'] );

        if ( $post_types ) {

            foreach ( $post_types as $graphql_type ) {

                register_graphql_field( $graphql_type, 'schema_package_jsonld', array(
                    'type'        => 'String',
                    'description' => esc_html__( 'Schema Package JSON-LD', 'schema-package' ),
                    'resolve'     => 'smpg_resolve_wpgraphql_jsonld',
                ) );

            }

        }

    }            
    
}

/**
 * Resolver for the GraphQL `jsonld` field.
 *
 * @param array $post WPGraphQL post object.
 * @return string JSON-LD schema.
 */
function smpg_resolve_wpgraphql_jsonld( $post ) {

    global $smpg_settings; 
    $post_id   = isset( $post->ID ) ? (int) $post->ID : 0;
    
    if ( $post_id > 0 ){

        $json_ld = smpg_get_json_ld( $post_id );

        return smpg_get_json_ld_based_on_constant( $json_ld, $smpg_settings );        

    }
        
}

//Expose Jsonld in WPGraphQL ends here

//Expose Jsonld in WordPress REST API starts here
add_action( 'rest_api_init', 'smpg_register_jsonld_rest_field' );

function smpg_register_jsonld_rest_field() {
        	
    global $smpg_settings; 
    
    if ( empty( $smpg_settings['json_ld_in_rest'] ) ) {
        return;
    }

    if ( smpg_is_admin_rest_request() ) {
		return;
	}
    
    $post_types = apply_filters( 'smpg_jsonld_rest_for_post_types', [ 'post' ] );

    if ( $post_types ) {

        foreach ( $post_types as $value ) {
     
            register_rest_field(
            $value,
            'schema_package_jsonld',
                array(
                    'get_callback' => 'smpg_get_jsonld_for_rest',
                    'schema'       => null,
                )
            );

        }

    }    	

}

function smpg_get_jsonld_for_rest( $post_arr ) {

    if ( isset( $post_arr['id'] ) ) {
        return smpg_get_json_ld( $post_arr['id'] );
    }
	
}
//Expose Jsonld in WordPress REST API ends here
add_action( 'init', 'smpg_json_ld_init');

function smpg_json_ld_init(){

    if ( is_admin() || ( defined('REST_REQUEST') && REST_REQUEST ) ) {
        return; 
    }

    smpg_manage_conflict();

    add_action('wp_head', 'smpg_json_ld_output');    
    ob_start('smpg_clean_other_format_schema');            
            
}


function smpg_json_ld_output() {
    
	global $smpg_settings;        
    $json_ld = apply_filters( 'smpg_filter_final_json_ld', smpg_get_json_ld() );    

    if ( ! empty($json_ld) ) {
        
		echo "\n\n";
		echo '<!-- schema.org data generated by Schema Package v'.esc_attr(SMPG_VERSION).' -->';
		echo "\n";
		echo '<script type="application/ld+json" class="smpg-json-ld">';
        echo "\n";

        if ( ! empty( $smpg_settings['minified_json'] ) &&  !empty( $smpg_settings['escaped_unicode_json'] ) ) {            

            echo wp_json_encode( $json_ld );

        }else{
            //phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped	-- Reason: already escaped
            echo smpg_get_json_ld_based_on_constant( $json_ld, $smpg_settings );
            
        }        
		
        echo "\n";
		echo '</script>';
		echo "\n\n";		

	}

}

function smpg_get_json_ld_based_on_constant( $json_ld, $smpg_settings ) {

    if ( ! empty( $smpg_settings['minified_json'] ) ) {
        return wp_json_encode( $json_ld, JSON_UNESCAPED_UNICODE );
    }elseif( ! empty( $smpg_settings['escaped_unicode_json'] ) ){                
        return wp_json_encode( $json_ld, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES );
    }else{
        return wp_json_encode( $json_ld, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE );
    }

}

function smpg_get_json_ld( $post_id = null ) {

    global $post;

    $post_id     = $spg_id = null;
    $response    = $spg_schema_meta = [];            
    
    if ( is_tax() || is_category() || is_tag() ) {

        $spg_id = get_queried_object_id();
        $spg_schema_meta = get_term_meta( $spg_id, '_smpg_schema_meta', true );      

        //Carousel schema markup addition
        $carousel_schema_ids = smpg_get_schema_ids( 'smpg_cached_key_carousel_schema' , 'smpg_carousel_schema' );
    
        if ( ! empty( $carousel_schema_ids ) ) {

            foreach ( $carousel_schema_ids as $id ) {
                
                $schema_meta = get_post_meta( $id );
                
                if ( isset( $schema_meta['_current_status'][0] ) && $schema_meta['_current_status'][0] == 1 ) {
                    
                    if ( smpg_is_carousel_placement_matched( $schema_meta ) ) {

                        $carousel_json_ld = smpg_prepare_carousel_json_ld( $schema_meta );

                        if ( ! empty( $carousel_json_ld ) ) {
                            $response[] = $carousel_json_ld;
                        }
                        

                    }

                }   
                        
            }

        }


        ///
    }
    
    //Singular schema markup addition

    if ( is_singular() || (  defined( 'REST_REQUEST' ) && REST_REQUEST  ) ) {

        $post_id = $post->ID;
        $spg_id  = $post_id;
        
        $spg_schema_meta = get_post_meta( $spg_id, '_smpg_schema_meta', true );        

        $singular_schema_ids = smpg_get_schema_ids( 'smpg_cached_key_singular_schema' , 'smpg_singular_schema' );
    
        if ( ! empty( $singular_schema_ids ) ) {
            
            foreach ( $singular_schema_ids as $id ) {
                
                $schema_meta = get_post_meta( $id );            
                
                if ( isset( $schema_meta['_current_status'][0] ) && $schema_meta['_current_status'][0] == 1 ) {
                    if ( smpg_is_singular_placement_matched( $schema_meta, $post_id ) ) {

                        $global_json_ld = smpg_prepare_global_json_ld( $schema_meta, $post_id );

                        if ( ! empty( $global_json_ld ) ) {
                            $response[] = $global_json_ld;
                        }
                        
                    }
                }            
            }

        }

    }            

    if ( is_author() ) {

        $spg_id = get_queried_object_id();        
        $spg_schema_meta = get_user_meta( $spg_id, '_smpg_schema_meta', true );      
    }

    //Schema Package Generator schema markup addition
        
    if ( ! empty( $spg_schema_meta ) && is_array( $spg_schema_meta ) ) {

        foreach ( $spg_schema_meta as $meta ) {
            
            if ( isset( $meta['is_enable'] ) && $meta['is_enable'] == 1 ) {

                $particular_data = smpg_prepare_particular_post_json_ld( $meta, $spg_id );                

                if ( ! empty( $particular_data ) ) {
                    $response[] = $particular_data;
                }
                
            }

        }

    }    
    //MISC Schema Output
    $breadcrumbs       = smpg_prepare_breadcrumbs_json_ld();    
    
    if(!empty($breadcrumbs)){
        $response [] = $breadcrumbs;
    }

    $profilepage       = smpg_prepare_profilepage_json_ld();    
    if(!empty($profilepage)){
        $response [] = $profilepage;
    }

    $site_navigation       = smpg_prepare_site_navigation_json_ld();    
    if(!empty($site_navigation)){
        $response [] = $site_navigation;
    }

    $website       = smpg_prepare_website_json_ld();    
    if(!empty($website)){
        $response [] = $website;
    }

    $about_page    = smpg_prepare_about_page_json_ld();
    if(!empty($about_page)){
        $response [] = $about_page;
    }

    $contact_page  = smpg_prepare_contact_page_json_ld();  

    if(!empty($contact_page)){
        $response [] = $contact_page;
    }    
    
    return $response;
}
/**
 * To clean the microdata and rdfa data from the content
 * Return: String
 * Since : v1.0.0
 */
function smpg_clean_other_format_schema($content){
 
    global $smpg_settings;

    if ( ! empty( $smpg_settings['clean_micro_data'] ) ) {
        
         if ( class_exists( 'WP_HTML_Tag_Processor' ) ) {

            $processor = new WP_HTML_Tag_Processor( $content );

            while ( $processor->next_tag() ) {

                $processor->remove_attribute( 'itemscope' );
                $processor->remove_attribute( 'itemtype' );
                $processor->remove_attribute( 'itemprop' );                

            }
            
            $content = $processor->get_updated_html();
        }
    }
    
    if ( ! empty( $smpg_settings['clean_rdfa_data'] ) ) {
        
        if ( class_exists( 'WP_HTML_Tag_Processor' ) ) {

            $processor = new WP_HTML_Tag_Processor( $content );

            while ( $processor->next_tag() ) {
                // Skip <meta> tags
                if ( 'META' === $processor->get_tag() ) {
                    continue;
                }

                // Remove RDFa attributes if present
                if ( $processor->get_attribute( 'property' ) ) {
                    $processor->remove_attribute( 'property' );
                }

                if ( $processor->get_attribute( 'typeof' ) ) {
                    $processor->remove_attribute( 'typeof' );
                }
            }

            $content = $processor->get_updated_html();
        }
    }
    
    return $content;
}

function smpg_manage_conflict() {

    global $smpg_settings;

    if ( ! empty( $smpg_settings['manage_conflict'] ) ) {

        foreach ($smpg_settings['manage_conflict'] as $value) {
            
            switch ($value) {

                case 'woocommerce':                    
                    if(class_exists('WooCommerce')){            
                        remove_action( 'wp_footer', [ WC()->structured_data, 'output_structured_data' ], 10 ); // This removes structured data from all frontend pages                                                
                    }                
                    break;                                
                case 'yetanotherstarsrating':                    
                    remove_filter('the_content', 'yasr_add_schema');  
                    break;                                
                case 'kkstarratings':                    
                    remove_action('wp_head', 'Bhittani\StarRating\structured_data');
                    break;                 
                case 'wooeventmanager':                    
                    remove_action('wp_head', 'mep_event_rich_text_data');    
                    break;  
                case 'wpeventmanager':                    
                    if(class_exists('WP_Event_Manager_Post_Types')){
                        remove_action( 'wp_footer', [ WP_Event_Manager_Post_Types::instance(), 'output_structured_data' ], 10 ); 
                    }  
                    break;
                case 'theeventscalendar':                    
                    add_filter('tribe_json_ld_event_data', 'smpg_remove_the_events_calendar_json_ld',10,2);  
                    break;
                case 'wppostratings':                    
                    add_filter('wp_postratings_schema_itemtype', '__return_false');
                    add_filter('wp_postratings_google_structured_data', '__return_false');  
                    break;
                case 'rankmath':                    
                    add_action( 'rank_math/json_ld', 'smpg_remove_rank_math_json_ld',99 );   
                    break;
                case 'yoastseo':                    
                    add_filter('wpseo_json_ld_output', '__return_false');         
                    smpg_remove_yoast_product_json_ld();                  
                    break;                
                case 'theseoframework':                    
                    add_filter('the_seo_framework_receive_json_data', '__return_null');  
                    break;
                case 'squirrlyseo':                    
                    add_filter('sq_json_ld', '__return_false',99);   
                    break;
                case 'smartcrawl':                    
                    add_filter('wds-schema-data', '__return_false');   
                    break;
                case 'seopress':                    
                    add_action('wp_head', 'smpg_seo_press_remove_json_ld',0);    
                    break;
                case 'wpeventmanager':                    
                    if(class_exists('WP_Event_Manager_Post_Types')){
                        remove_action( 'wp_footer', [ WP_Event_Manager_Post_Types::instance(), 'output_structured_data' ], 10 ); 
                    }  
                    break;    
                
                default:
                
                    break;
            }

        }

    }
    
}

function smpg_remove_the_events_calendar_json_ld( $data, $args ){
        
    return [];
}

function smpg_remove_yoast_product_json_ld(){
         
    global $wp_filter;
            
    if(isset($wp_filter['wp_footer']) && is_object($wp_filter['wp_footer'])){
      
     $callbacks =  $wp_filter['wp_footer']->callbacks;
     
     if(is_array($callbacks)){
     
         foreach($callbacks as $key=>$actions){
             
         if(is_array($actions)){
         
             foreach ($actions as $actualKey => $priorities){
             
                 if(is_array($priorities['function'])){
                 
                     if(is_object($priorities['function'][0])){
                     
                         if ($priorities['function'][0] instanceof WPSEO_WooCommerce_Schema && $priorities['function'][1] == 'output_schema_footer') {
                              unset($wp_filter['wp_footer']->callbacks[$key][$actualKey]);
                         }
                         
                     }
                                                                     
                 }
                                                                             
             }
             
         }    
                                        
       }
         
     }   
             
   }                       

 }
 function smpg_seo_press_remove_json_ld(){
    remove_action('wp_head', 'seopress_social_accounts_jsonld_hook',1);
    remove_action('wp_head', 'seopress_social_website_option',1);                                    
 }
 function smpg_remove_rank_math_json_ld($entry){
    return [];  
 }